[package]
name = "opengl-squares"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "0.14.0"
glam = "0.28.0"
glutin = "0.32.0"
glutin-winit = "0.5.0"
rand = "0.8.5"
winit = { version = "0.30.3", default-features = false, features = [
	"rwh_06",
	"x11",
	"wayland",
] }
